### ISSUE TITLE
Make an account

### ISSUE THREAD

**Issue by jakeaustinlewis** [pantzed/lovel-up#5]
As a user, I want to be able to create an account. An account will consist of:
-username (email)
-password (string)
-first name (string)
-last name (string)
-birthdate (date)
-gender (string)
-seeking_male (boolean)
-seeking_femaile (boolean)
-photo_1 (binary)
-photo_2 (binary)
-photo_3 (binary)
-photo_4 (binary)
-photo_5 (binary)
-description (string)
-total_exp (integer)
-level_exp (integer
-religion (string)

**Comment by pantzed** [comment]
Partially completed.

Still need...

- [ ] New user form should require user upload photo

- [ ] On successful new user post, users should see rendered profile page with their information
